<?php

/**
 * Copyright © 2016 Valiton GmbH
 *
 * This file is part of Harbourmaster Drupal Plugin.
 *
 * Harbourmaster Drupal Plugin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Harbourmaster Drupal Plugin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Harbourmaster Drupal Plugin.  If not, see <http://www.gnu.org/licenses/>.
 */

function hms_install() {
  $link = \Drupal\Core\Link::fromTextAndUrl(t('admin config page'), \Drupal\Core\Url::fromUri('internal:/admin/config/people/hms'));
  drupal_set_message(
    t(
      'For the HMS module to work properly, you still have to configure the module on the <a href=":link">configuration page</a>',
      [':link' => '/admin/config/people/hms']
    ),
    'warning'
  );
}

function hms_library_info_build() {
  $url = \Drupal::config('hms.settings')->get('user_manager_url');
  $libraries = [];
  $libraries['usermanager.app'] = [
    'dependencies' => [
      'core/jquery',
    ],
    'js' => [
      $url . '/usermanager/prod/js/libs.js' => [
        'type' => 'external',
      ],
      $url . '/usermanager/prod/js/app.js' => [
        'type' => 'external',
      ],
    ],
    'css' => [
      'module' => [
        $url . '/styles/hms-widget.css' => [
          'type' => 'external',
        ],
      ],
    ],
  ];
  return $libraries;
}

function hms_theme() {

  $theme['usermanager'] = [
    'variables' => [],
    'template' => 'usermanager',
  ];

  return $theme;
}